name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        env:
          IMAGE_URL: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REGISTRY_REPO }}/miniclue-be:${{ github.ref_name }}
        run: |
          docker build -t $IMAGE_URL .
          docker push $IMAGE_URL

      - name: Deploy to Cloud Run (Production)
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: miniclue-be-prod
          image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REGISTRY_REPO }}/miniclue-be:${{ github.ref_name }}
          region: ${{ secrets.GCP_REGION }}
          flags: "--allow-unauthenticated"
          env_vars: |
            ENV=production
            APP_ENV=production
            DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}
            SUPABASE_JWT_SECRET=${{ secrets.SUPABASE_JWT_SECRET }}
            SUPABASE_S3_URL=${{ secrets.SUPABASE_S3_URL }}
            SUPABASE_S3_BUCKET=${{ secrets.SUPABASE_S3_BUCKET }}
            SUPABASE_S3_REGION=${{ secrets.SUPABASE_S3_REGION }}
            SUPABASE_S3_ACCESS_KEY=${{ secrets.SUPABASE_S3_ACCESS_KEY }}
            SUPABASE_S3_SECRET_KEY=${{ secrets.SUPABASE_S3_SECRET_KEY }}
            GCP_PROJECT_ID_PROD=${{ secrets.GCP_PROJECT_ID }}

      - name: Show Cloud Run URL
        run: echo "Deployed to ${{ steps.deploy.outputs.url }}"
